merged test feature branch to master

diff --git a/.circleci/config copy.yml b/.circleci/config copy.yml
--- a/.circleci/config copy.yml
+++ b/.circleci/config copy.yml
@@ -211,22 +211,22 @@ jobs:
       - destroy-environment:
                 workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
   run-migrations:
-    # Docker image here that supports NodeJS
     docker:
-      - image: cimg/node:18.8.0
+      - image: amazon/aws-cli
     steps:
       - checkout
-      - restore_cache:
-          keys: [backend-build]
       - run:
           name: Run migrations
           command: |
             cd backend
+            yum -y install tar gzip
+            rm -r /var/cache/yum
+            yum clean all
+            curl -sL https://rpm.nodesource.com/setup_lts.x | bash -
+            yum -y install nodejs
             npm install
             # Run and save the migration output
             npm run migrations > migrations_dump.txt
-            echo "view migrations_dump.txt ..."
-            cat migrations_dump.txt
       - run:
           name: Send migration results to memstash
           command: |
@@ -237,7 +237,6 @@ jobs:
      # Here's where you will add some code to rollback on failure      
       - destroy-environment:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-
   deploy-frontend:
     docker:
       # Docker image here that supports AWS CLI
@@ -251,7 +250,7 @@ jobs:
           name: Install dependencies
           command: |
             yum -y install tar gzip
-            rm -rf /var/cache/yum/*
+            rm -r /var/cache/yum
             yum clean all
             curl -sL https://rpm.nodesource.com/setup_lts.x | bash -
             yum -y install nodejs
@@ -281,9 +280,6 @@ jobs:
       # Here's where you will add some code to rollback on failure      
       - destroy-environment:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}              
-      - revert-migrations:
-          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7} 
-
   deploy-backend:
     docker:
       # Docker image here that supports Ansible
@@ -318,15 +314,15 @@ jobs:
             cd .circleci/ansible
             echo "Contents  of the inventory.txt file is -------"
             cat inventory.txt
-            ansible-playbook -vv -i inventory.txt deploy-backend.yml
+            ansible-playbook -i inventory.txt deploy-backend.yml
       # Here's where you will add some code to rollback on failure  
       - destroy-environment:
-          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7} 
-      - revert-migrations:
-          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7} 
-   
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}    
       
   smoke-test:
+    shell: /bin/sh -leo pipefail
+    environment:
+      BASH_ENV: /etc/profile
     docker:
       - image: python:3.7-alpine3.11
     steps:
@@ -341,11 +337,17 @@ jobs:
           name: Get backend url
           command: |
             export BACKEND_IP=$(aws ec2 describe-instances \
-                            --filters Name=tag:Name,Values="backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-                            --query 'Reservations[*].Instances[*].PublicIpAddress' \
-                            --output text)
-            export API_URL="http://${BACKEND_IP}:3030"
+                              --filters Name=tag:Name,Values="backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+                              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+                              --output text)
             echo "${BACKEND_IP}"
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo $API_URL
+            sh -c env
+      - run:
+          name: Backend smoke test.
+          command: |
+            sh -c env
             echo "${API_URL}"
             if curl "${API_URL}/api/status" | grep "ok"
             then
@@ -373,83 +375,41 @@ jobs:
           workflow_id: ${CIRCLE_WORKFLOW_ID:0:7} 
 
 
-  cloudfront-update:
-    docker:
-      # Docker image here that supports AWS CLI
-      - image: amazon/aws-cli
-    steps:
-      # Checkout code from git
-      - checkout
-      - run:
-          name: Install dependencies
-          command: |
-           # install tar utility
-            yum install -y tar gzip
-      - run:
-          name: Update cloudfront distribution
-          command: |
-            export OldWorkflowID=$(aws cloudformation \
-                    list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
-                    --no-paginate --output text)
-            echo $OldWorkflowID >> ~/OldWorkflowID.txt
-            cat ~/OldWorkflowID.txt
+#   cloudfront-update:
+#     docker:
+#       # Docker image here that supports AWS CLI
+#     steps:
+#       # Checkout code from git
+#       - run:
+#           name: Install dependencies
+#           command: |
+#             # your code here
+#       - run:
+#           name: Update cloudfront distribution
+#           command: |
+#             # your code here
+#       # Here's where you will add some code to rollback on failure  
 
-            aws cloudformation deploy \
-            --template-file .circleci/files/cloudfront.yml \
-            --stack-name InitialStack \
-            --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
-            --tags project=udapeople
-
-            echo OldWorkflowID: "${OldWorkflowID}"
-            echo CIRCLE_WORKFLOW_ID "${CIRCLE_WORKFLOW_ID:0:7}"
-      - persist_to_workspace:
-          root: ~/
-          paths:
-            - OldWorkflowID.txt
-      # Here's where you will add some code to rollback on failure  
-      - destroy-environment:  
-          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7} 
-      - revert-migrations:
-          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7} 
-  cleanup:
-    docker:
-      # Docker image here
-      - image: amazon/aws-cli
-    steps:
-      # Checkout code from git
-      - checkout
-      - run:
-          name: Install dependencies
-          command: |
-            # install tar utility
-            yum install -y tar gzip
-      - attach_workspace:
-          at: ~/
-      - run:
-          name: Get old stack workflow id and remove old stacks and files
-          command: |
-            # Fetch the Old workflow ID
-            cat ~/OldWorkflowID.txt
-            OldWorkflowID=$(cat ~/OldWorkflowID.txt)
-
-            echo OldWorkflowID: "${OldWorkflowID}"
-            echo CIRCLE_WORKFLOW_ID "${CIRCLE_WORKFLOW_ID:0:7}"
+# cleanup:
+#     docker:
+#       # Docker image here
+#     steps:
+#       # Checkout code from git
+#       - run:
+#           name: Get old stack workflow id
+#           command: |
+#             # your code here
+#             export OldWorkflowID="the id here"
+#             export STACKS=[] #put the list of stacks here
+#       - run:
+#           name: Remove old stacks and files
+#           command: |
+#             if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+#             then
+#               # your code here
+#             fi
             
-            # Fetch the stack names          
-            export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
-                    --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
-            echo Stack names: "${STACKS[@]}"
 
-            if [[ "${CIRCLE_WORKFLOW_ID:0:7}" != "${OldWorkflowID}" ]]
-            then
-              aws s3 ls
-              aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
-              aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
-              aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
-            else
-              echo "no previous workflows to clean up........."
-            fi
-                        
 workflows:
   default:
     jobs:
@@ -468,39 +428,18 @@ workflows:
           requires: [test-frontend, test-backend, scan-frontend, scan-backend]
           filters:
             branches:
-              only: [master]
+              only: [test-feature-branch]
       - configure-infrastructure:
           requires: [deploy-infrastructure]
-          filters:
-            branches:
-              only: [master]
       - run-migrations:
           requires: [configure-infrastructure]
-          filters:
-            branches:
-              only: [master]
       - deploy-frontend:
           requires: [run-migrations]
-          filters:
-            branches:
-              only: [master]
       - deploy-backend:
           requires: [run-migrations]
-          filters:
-            branches:
-              only: [master]
       - smoke-test:
           requires: [deploy-backend, deploy-frontend]
-          filters:
-            branches:
-              only: [master]
-      - cloudfront-update:
-          requires: [smoke-test]
-          filters:
-            branches:
-              only: [master]
-      - cleanup:
-          requires: [cloudfront-update]
-          filters:
-            branches:
-              only: [master]
+      # - cloudfront-update:
+      #     requires: [smoke-test]
+      # - cleanup:
+      #     requires: [cloudfront-update]
